### ISSUE TITLE
Example results in xml parse error

### ISSUE THREAD

**Issue by tpilz** [ukcp-data/ukcp-api-client#2]
Hi,

the example (and any URL that worked with the GUI) results in an error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/projects/transformar/src/ukcp-api-client/ukcp_api_client/client.py", line 112, in submit
    status_url = get_status_url(response.text)
  File "/p/projects/transformar/src/ukcp-api-client/ukcp_api_client/utils.py", line 57, in get_status_url
    root = ET.fromstring(xml)
  File "/p/projects/transformar/bin/conda/transformarenv/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 50, column 2
```
I use Python 3.9.7.

Any suggestions?

**Comment by agstephens** [comment]
Hi @tpilz , thanks for raising this. I am looking at updated it to python3.7+

**Comment by agstephens** [comment]
@tpilz, I have updated the code and the tests now work for me. Please give it a try.
Tagging: @antony-wilson

**Comment by tpilz** [comment]
@agstephens @antony-wilson
Thanks for fixing. Now jobs are submitted but they (at least the two examples provided here) fail with an error: `"UnboundLocalError= local variable 'time_index' referenced before assignment"`. It seems this is somehow related to the data repository processing the job or the specific example rather than the python api.
